### ISSUE TITLE
Schematic Changes Needed

### ISSUE THREAD

**Issue by rachmo** [REVrobotics/Blinkin-Firmware#1]
- [x] Add +5V to headers

- [x] Add RST to headers a. would be nice to have by the TX and RX pins on J4

- [x] Switch PWM Signal input from D6 to D2 (Interrupt 0) or D3 (Int 1)

- [x] Connect Signal D2 [was D6] to screw terminal

- [x] Switch to 16mHz crystal to improve team programming

**Comment by rachmo** [comment]
@ILAMtitan  working on switching the servo input, and I think we messed up on the Servo Input. D6 was supposed to be the WS2811 data output and Servo input is D8, I guess that's why we thought it wasn't connected on the board? 

Does servo input need to be D2 still or is D8 okay?

**Comment by ILAMtitan** [comment]
The Arduino only has IO interrupts on D2 or D3. We could do it in software on D8, but it wouldn't work as well.
