### ISSUE TITLE
Consider Device Change to Atmega328p

### ISSUE THREAD

**Issue by rachmo** [REVrobotics/Blinkin-Firmware#2]
> Bart: The Atmega328p would make the toolchain much easier to use for teams than the 328pb

**Comment by ILAMtitan** [comment]
It took me a significant effort to make the pb work, and I have an IAR programer. The 328p with the Arduino bootloader pre-flashed would make it significantly easier for teams to work with custom code.

**Comment by rachmo** [comment]
@ILAMtitan yes, I agree with this, that along with the apparent scarcity of the -pb model even this long after silicon release.  I'm making the change over to the -p model, just trying to figure out the best way to not have to completely remap all the pins to make the layout work.

**Comment by rachmo** [comment]
Changed over to 328p
